#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonoDroid.LocationService.Bootstrap.Resource", IsApplication=true)]

namespace MonoDroid.LocationService.Bootstrap
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btnExportData = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int btnServiceActive = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int btnServiceControl = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int tvGpsStatus = 2131034115;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LocationMonitoringServiceLabel = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LocationMonitoringServiceStarted = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int LocationMonitoringServiceStopped = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int StartService = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
